Repository DIT112-V21/group-07, pull requests merged in 2021-05, with the labels that each got.

#59 Thumbstick, Speedbar, and Speedometer
  UI/app/src/main/AndroidManifest.xml
  UI/app/src/main/java/com/example/pathfinder/Activities/DashboardActivity.java
  UI/app/src/main/java/com/example/pathfinder/Activities/MainActivity.java
  UI/app/src/main/java/com/example/pathfinder/Activities/ModeType.java
  UI/app/src/main/java/com/example/pathfinder/Activities/ThumbstickView.java
  UI/app/src/main/res/layout/activity_dashboard.xml
  UI/app/src/main/res/values/strings.xml
  UI/build.gradle
  arduino/smartcar/smartcar.ino
Labels: Sprint #2, task

#69 Measure traveled distance
  UI/app/src/main/java/com/example/pathfinder/Activities/DashboardActivity.java
  UI/app/src/main/res/values/strings.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #3, User Story

#72 Driver access possibilities
  UI/app/build.gradle
  UI/app/src/main/AndroidManifest.xml
  UI/app/src/main/java/com/example/pathfinder/Activities/DashboardActivity.java
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverLogin.java
  UI/app/src/main/java/com/example/pathfinder/Activities/MainActivity.java
  UI/app/src/main/java/com/example/pathfinder/Activities/UserSelection.java
  UI/app/src/main/java/com/example/pathfinder/FirstFragment.java
  UI/app/src/main/java/com/example/pathfinder/SecondFragment.java
  UI/app/src/main/res/layout/activity_dashboard.xml
  UI/app/src/main/res/layout/activity_main.xml
  UI/app/src/main/res/layout/content_dashboard.xml
  UI/app/src/main/res/layout/driver_login.xml
  UI/app/src/main/res/layout/fragment_first.xml
  UI/app/src/main/res/layout/fragment_second.xml
  UI/app/src/main/res/layout/user_selection.xml
  UI/app/src/main/res/navigation/nav_graph.xml
  UI/app/src/main/res/values/strings.xml
  UI/app/src/test/java/com/example/pathfinder/DriverLoginTest.java
  UI/build.gradle
  UI/gradle/wrapper/gradle-wrapper.properties
Labels: Sprint #3

#73 Camera feature
  UI/app/build.gradle
  UI/app/src/main/AndroidManifest.xml
  UI/app/src/main/java/com/example/pathfinder/Activities/DashboardActivity.java
  UI/app/src/main/res/layout/activity_dashboard.xml
  UI/app/src/main/res/values/strings.xml
  UI/gradle/wrapper/gradle-wrapper.properties
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, Sprint #2, Sprint #3, User Story

#79 Driver login tests
  .github/workflows/GUI_CI.yml
  UI/app/build.gradle
  UI/app/src/androidTest/java/com/example/pathfinder/Activities/DriverLoginTest.java
  UI/app/src/androidTest/java/com/example/pathfinder/Activities/ToastMatcher.java
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverLogin.java
  UI/app/src/main/res/values/strings.xml
Labels: Sprint #4

#87 Update README.md
  README.md
Labels: documentation, high, task

#84 Cruise control & Limit speed
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  UI/app/src/main/res/layout/activity_driver_dashboard.xml
Labels: Sprint #4

#85 Passenger screen
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/ModeType.java
  UI/app/src/main/java/com/example/pathfinder/Activities/PassengerDashboard.java
  UI/app/src/main/res/layout/activity_driver_dashboard.xml
  UI/app/src/main/res/layout/activity_passenger_dashboard.xml
  UI/app/src/main/res/values/colors.xml
  UI/app/src/main/res/values/strings.xml
Labels: Sprint #4, User Story, high, task

#89 Bug motion accuracy
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/ThumbstickView.java
Labels: Sprint #4, bugfix

#88 Bus route
  UI/app/build.gradle
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/PassengerDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/StopListAdapter.java
  UI/app/src/main/java/com/example/pathfinder/Model/BusLine.java
  UI/app/src/main/java/com/example/pathfinder/Model/BusRoute.java
  UI/app/src/main/java/com/example/pathfinder/Model/Stop.java
  UI/app/src/main/res/anim/fade_away_animation.xml
  UI/app/src/main/res/anim/slide_up_animation.xml
  UI/app/src/main/res/drawable/rounded_corner.xml
  UI/app/src/main/res/drawable/stop_list_background.xml
  UI/app/src/main/res/layout/activity_driver_dashboard.xml
  UI/app/src/main/res/layout/activity_passenger_dashboard.xml
  UI/app/src/main/res/layout/bus_route.xml
  UI/app/src/main/res/layout/bus_route_passenger.xml
  UI/app/src/main/res/layout/stop_row.xml
  UI/app/src/main/res/values/strings.xml
  UI/app/src/test/java/com/example/pathfinder/DriverLoginTest.java
  UI/app/src/test/java/com/example/pathfinder/Model/BusLineTest.java
  UI/build.gradle
Labels: Sprint #4, high

#95 Cross-process communication and minor debugging
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/PassengerDashboard.java
  UI/app/src/main/res/layout/activity_driver_dashboard.xml
  UI/app/src/main/res/layout/activity_passenger_dashboard.xml
Labels: Sprint #4

#97 Removing Cmake-build-debug directory
  cmake-build-debug/CMakeFiles/3.19.2/CMakeCCompiler.cmake
  cmake-build-debug/CMakeFiles/3.19.2/CMakeSystem.cmake
  cmake-build-debug/CMakeFiles/3.19.2/CompilerIdC/CMakeCCompilerId.c
  cmake-build-debug/CMakeFiles/3.19.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
Labels: Sprint #4, fixed, task

#99 "Cmake-build-debug is added into .gitignore"
  .gitignore
Labels: fixed, task

#98 Code quality & documentation
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverLogin.java
  UI/app/src/main/java/com/example/pathfinder/Activities/PassengerDashboard.java
  UI/app/src/main/java/com/example/pathfinder/Activities/ThumbstickView.java
  arduino/smartcar/smartcar.ino
Labels: documentation

#100 [Bug] "/SmartCar/Odometer" is added to "driverDasboard"
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
Labels: Sprint #4, bug, fixed, high

#103 [Bug_Fix] Cruise control affecting steering and throttle uncontrollably
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  arduino/smartcar/smartcar.ino
Labels: Sprint #4, bugfix

#90 Smartcar and SMCE references
  .github/workflows/Android_CI.yml
  .github/workflows/Arduino-Build&Test.yml
  .github/workflows/Arduino-Build.yml
  .github/workflows/Arduino-Test.yml
  CMakeLists.txt
  README.md
Labels: Sprint #4, documentation, fixed, high, task

#105 Bug disable cruise control #104
  UI/app/src/main/java/com/example/pathfinder/Activities/DriverDashboard.java
  arduino/smartcar/smartcar.ino
Labels: Sprint #4, bugfix

#107 Badge & testing link
  .github/workflows/Android_CI.yml
  README.md
Labels: Sprint #4, bug, fixed, high, task

#108 Updated Readme
  README.md
Labels: Sprint #4, fixed, task

#109 Pathfinder demo video link added to README
  README.md
Labels: Assignment, task
