Repository DIT112-V21/group-07, pull requests merged in 2021-04, with the labels that each got.

#26 CI-build-adding-MQTT-and-WIFI
  .github/workflows/arduino-build.yml
Labels: Sprint #1, User Story, high

#27 Adding "install camera library"
  .github/workflows/arduino-build.yml
Labels: Sprint #1, User Story, high

#30 Slow down smoothly
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User Story, high

#32 Measure the distance
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User Story

#33 Unexpected obstacles behavior
  .idea/.gitignore
  .idea/group-07.iml
  .idea/modules.xml
  .idea/vcs.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User Story

#34 Measure the distance
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, User Story

#36 Master merge
  arduino/smartcar/smartcar.ino
Labels: Sprint #1, task

#37 Removed duplicates in nav_graph.xml
  UI/app/src/main/res/navigation/nav_graph.xml
Labels: bug

#38 Create GUI_CI.yml
  .github/workflows/GUI_CI.yml
Labels: task

#54 Bug side avoidance
  arduino/smartcar/smartcar.ino
Labels: Sprint #2

#56 Unit_Test
  .github/workflows/GUI_CI.yml
Labels: Sprint #2, high, task

#57 Bug fix slow down smoothly - #50
  arduino/smartcar/smartcar.ino
Labels: bugfix
